# -*- coding: utf-8 -*-
"""Reto1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DC61wcn3Ao2mnDsMl2KgG07a3h6HDpPN
"""

Semilla_J67 = int(input())

Semilla_M15 = (Semilla_J67*2)+4
Semilla_R99 = (Semilla_J67 + Semilla_M15) // 5

print(Semilla_J67, end=" ")
print(Semilla_M15, end=" ")
print(Semilla_R99)

if Semilla_R99 > 80:
  print("cuatro")

elif Semilla_R99 >= 41 <= 80:
  print("tres")

elif Semilla_R99 >= 21 <= 40:
  print("dos")

elif Semilla_R99 >= 0 <= 20:
  print("uno")